listenAddress: 0.0.0.0:6155
clusterListenAddress: 127.0.0.1:0
httpClusterListenAddress: 0.0.0.0:6156
httpNodeListenAddress: 0.0.0.0:16156
debugListenAddress: 0.0.0.0:16155

hostID:
    resolver: hostname

client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority
    clusterConnectConsistencyLevel: any
    writeTimeout: 10s
    fetchTimeout: 15s
    connectTimeout: 20s
    writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
    fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
    backgroundHealthCheckFailLimit: 4
    backgroundHealthCheckFailThrottleFactor: 0.5

gcPercentage: 100

# insert new series asynchronously
writeNewSeriesAsync: true
# insert new series ~1MM/sec max
writeNewSeriesLimitPerSecond: 1048576
# insert new series batched every 2ms
writeNewSeriesBackoffDuration: 2ms

cache:
    series:
        policy: recently_read

bootstrap:
    bootstrappers:
        - filesystem
        - peers
        - noop-all
    fs:
        numProcessorsPerCPU: 0.125 # 4 cpus for 32 node cpu
    peers:
        fetchBlocksMetadataEndpointVersion: v2

tickInterval: 10m

commitlog:
    flushMaxBytes: 524288 # 524kb
    flushEvery: 1s
    queue:
        calculationType: fixed
        size: 2097152 # 2MM: if node is taking 150k/s then ~13s
    retentionPeriod: 24h
    blockSize: 10m

fs:
    filePathPrefix: /var/m3em-agent/m3db-data
    writeBufferSize: 65536
    dataReadBufferSize: 65536
    infoReadBufferSize: 64
    seekReadBufferSize: 4096
    throughputLimitMbps: 100.0
    throughputCheckEvery: 128

repair:
    enabled: false
    interval: 2h
    offset: 30m
    jitter: 1h
    throttle: 2m
    checkInterval: 1m

pooling:
    blockAllocSize: 16
    type: simple
    seriesPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    blockPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    encoderPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    closersPool:
        size: 104857
        lowWatermark: 0.7
        highWatermark: 1.0
    contextPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    segmentReaderPool:
        size: 16384
        lowWatermark: 0.7
        highWatermark: 1.0
    iteratorPool:
        size: 2048
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlockMetadataResultsPool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlocksMetadataResultsPool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    hostBlockMetadataSlicePool:
        size: 131072
        capacity: 3
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataSlicePool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataSlicePool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    identifierPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    bytesPool:
        buckets:
            - capacity: 16
              size: 524288
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 32
              size: 262144
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 64
              size: 131072
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 128
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 256
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1440
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 4096
              size: 8192
              lowWatermark: 0.7
              highWatermark: 1.0

logging:
    level: info
    stdout: true

metrics:
    m3:
        hostPort: 127.0.0.1:9052
        service: statsdex_m3dbnode
        env: production
        includeHost: true
    samplingRate: 0.01
    extended: moderate
    sanitization: m3

config:
    service:
        env: dtest_integration
        zone: sjc1
        service: statsdex_m3dbnode
        cacheDir: /var/lib/m3kv
        etcdClusters:
            - zone: sjc1
              endpoints:
                  - m3-kv01-sjc1:2379
                  - m3-kv02-sjc1:2379
                  - m3-kv03-sjc1:2379
                  - m3-kv04-sjc1:2379
                  - m3-kv05-sjc1:2379

